apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  namespace: finflow
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
