server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: module-21-concurrency-race-conditions-distributed-locks

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
