package com.finflow.troubleshooting.module15;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.asyncDispatch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(classes = Module15Application.class)
@AutoConfigureMockMvc
public class CorrelationIdFilterTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    void testCustomCorrelationIdHeaderPreservedInResponse() throws Exception {
        String testCorrId = "CORR-XYZ-9999";

        MvcResult mvcResult = mockMvc.perform(post("/api/v1/orders/submit?orderId=ORD-101")
                        .header("X-Correlation-ID", testCorrId))
                .andExpect(request().asyncStarted())
                .andReturn();

        mockMvc.perform(asyncDispatch(mvcResult))
                .andExpect(status().isOk())
                .andExpect(header().string("X-Correlation-ID", testCorrId));
    }

    @Test
    void testMissingCorrelationIdHeaderAutoGenerated() throws Exception {
        MvcResult mvcResult = mockMvc.perform(post("/api/v1/orders/submit?orderId=ORD-102"))
                .andExpect(request().asyncStarted())
                .andReturn();

        MvcResult completedResult = mockMvc.perform(asyncDispatch(mvcResult))
                .andExpect(status().isOk())
                .andReturn();

        String generatedCorrId = completedResult.getResponse().getHeader("X-Correlation-ID");
        assertThat(generatedCorrId).isNotBlank();
    }
}
