server:
  port: 8090

spring:
  application:
    name: database-performance-deadlocks-lab
  datasource:
    url: jdbc:h2:mem:finflow_deadlock_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    hikari:
      pool-name: DeadlockTestPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
