spring:
  datasource:
    hikari:
      pool-name: FinFlowHikariPool
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 30000
      leak-detection-threshold: 2000
      validation-timeout: 250
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
