spring:
  application:
    name: payment-service-ch040
  lifecycle:
    timeout-per-shutdown-phase: 25s
  main:
    allow-bean-definition-overriding: false

server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200
